# Self-signed certificate authority
ca:
   root:
      dn: CN=elasticsearch,OU=Wazuh,O=Wazuh,L=California,C=US
      keysize: 2048
      validityDays: 3650
      pkPassword: none
      file: root-ca.pem

# Default values and global settings
defaults:
      validityDays: 3650
      pkPassword: none
      generatedPasswordLength: 12
      httpsEnabled: true

# Nodes certificates
nodes:
  - name: elasticsearch
    dn: CN=node-1,OU=Wazuh,O=Wazuh,L=California,C=US
    ip: 
      - <elasticsearch_IP>
  - name: kibana
    dn: CN=kibana,OU=Wazuh,O=Wazuh,L=California,C=US     
    ip:
      - <kibana_ip>                  

# Clients certificates
clients:
  - name: admin
    dn: CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US
    admin: true
  - name: filebeat
    dn: CN=filebeat,OU=Wazuh,O=Wazuh,L=California,C=US 
