## Single-node configuration

## Elasticsearch configuration

network.host: <elastic_ip_addr_node1>


# Clients certificates
clients:
  - name: admin
    dn: CN=admin,OU=Docu,O=Wazuh,L=California,C=US
    admin: true
  - name: filebeat
    dn: CN=filebeat,OU=Docu,O=Wazuh,L=California,C=US


# Kibana-instance
- <kibana_ip_addr>

# Wazuh-master-configuration
- <wazuh_master_ip_addr>
