installation:
  type: <installation-type>

certificates:
  elasticsearch:
    name: node1
    ip: 192.168.56.16
    name: node2
    ip: 192.168.56.16
    # name: <elasticsearch-node-name>
    # ip: <elasticsearch-node-ip>

  # Wazuh server nodes
  wazuh_servers:
    name: wazuh
    ip: 192.168.56.16
    # name: <wazuh-node-name>
    # ip: <wazuh-manager-ip>

  # Kibana node
  kibana:
    name: kibana
    ip: 192.168.56.16

## Wazuh cluster configuration
wazuh_cluster_config:
  cluster_name: cluster
  master_address: 192.168.56.16