## Single-node configuration

## Elasticsearch configuration

network.host: 192.168.56.16


# Clients certificates
clients:
  - name: admin
    dn: CN=admin,OU=Docu,O=Wazuh,L=California,C=US
    admin: true
  - name: filebeat
    dn: CN=filebeat,OU=Docu,O=Wazuh,L=California,C=US


# Kibana-instance
- 192.168.56.17

# Wazuh-master-configuration
- 192.168.56.17
