nodes:
  # Wazuh indexer server nodes
  indexer:
    name: wazuh-indexer-1
    ip: 10.10.121.100
    name: wazuh-indexer-2
    ip: 10.10.121.200
    # name: node-3
    # ip: <elasticsearch-node-ip>

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  wazuh_servers:
    name: wazuh-manager1
    ip: 10.10.121.100
    node_type: master
    name: wazuh-manager2
    ip: 10.10.121.200
    node_type: worker

  # Wazuh dashboard node
  dashboard:
    name: wazuh-dashboard-1
    ip: 10.10.121.200
