nodes:
  # Wazuh indexer server nodes
  indexer:
    name: <indexer-node-name>
    ip: <indexer-node-ip>
    # name: <elasticsearch-node-name>
    # ip: <elasticsearch-node-ip>

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  wazuh_servers:
    name: <wazuh-node-name>
    ip: <wazuh-manager-ip>
    # node_type: master
    # name: <wazuh-node-name>
    # ip: <wazuh-manager-ip>
    # node_type: worker

  # Wazuh dashboard node
  dashboard:
    name: <dashboard-node-name>
    ip: <dashboard-node-ip>
