name: Wazuh Packages pipeline for unattended installer testing

on: [push]

jobs:

  CentOS_7_unattended_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Unattended installation and test
        uses: './.github/actions/Docker/CentOS/7/'

  Ubuntu_Focal_unattended_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Unattended installation and test
        uses: './.github/actions/Docker/Ubuntu/Focal/'

  Ubuntu_Bionic_unattended_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Unattended installation and test
        uses: './.github/actions/Docker/Ubuntu/Bionic/'