name: Build Wazuh Packages - RPM - x86_64 and i386
on:
  pull_request:
    paths:
      - 'rpms/SPECS/*'
      - 'rpms/generate_rpm_package.sh'
  workflow_dispatch:
  workflow_call:

jobs:
  Wazuh-agent-rpm-package-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TYPE: [agent, manager]
        ARCHITECTURE : [x86_64, i386]
        exclude:
          - TYPE: manager
            ARCHITECTURE: i386
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            rpm_images:
              - 'rpms/CentOS/**'
              - 'rpms/build.sh'
            rpm_packages:
              - 'rpms/SPECS/**'
              - 'rpms/generate_rpm_package.sh'

      - name: Set tag and container name
        run: |
          if [ "${{ steps.changes.outputs.rpm_images }}" == "true" ]; then echo "TAG=${{ github.head_ref }}" >> $GITHUB_ENV; else echo "TAG=$(sed 's/\([0-9]*\.[0-9]*\)\.[0-9]*/\1/' $GITHUB_WORKSPACE/VERSION)" >> $GITHUB_ENV ; fi
          if [ "${{ matrix.ARCHITECTURE }}" == "x86_64" ]; then echo "CONTAINER_NAME=rpm_builder_x86" >> $GITHUB_ENV ; else echo "CONTAINER_NAME=rpm_builder_${{ matrix.ARCHITECTURE }}" >> $GITHUB_ENV ; fi

      - name: Download docker image for package building
        run: |
          bash $GITHUB_WORKSPACE/.github/actions/common-tools/pull_image_from_ghcr.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor}} $CONTAINER_NAME ${{ env.TAG }}

      - name: Build the ${{ matrix.ARCHITECTURE }} rpm Wazuh ${{ matrix.TYPE }} package
        working-directory: ./rpms
        run: |
          bash generate_rpm_package.sh -b master -t ${{ matrix.TYPE }} -a ${{ matrix.ARCHITECTURE }} --dev -j 2 --dont-build-docker --tag ${{ env.TAG }} -r test
          echo "PACKAGE_NAME=$(ls ./output | grep .rpm | head -n 1)" >> $GITHUB_ENV

      - name: Upload Wazuh ${{ matrix.TYPE }} ${{ matrix.ARCHITECTURE }} package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{github.workspace}}/rpms/output/${{ env.PACKAGE_NAME }}

  # Call-test-packages-workflow:
  #   needs: 
  #     - Wazuh-agent-rpm-package-builds
  #   uses: ./.github/workflows/test-install-and-enable-rpm.yml
  #   secrets: inherit