name: Build Wazuh Packages - RPM - All architectures
on:
  pull_request:
    paths:
      - 'rpms/SPECS/*'
      - 'rpms/generate_rpm_package.sh'
      - 'rpms/build.sh'
      - 'rpms/CentOS/*'
      - 'rpms/build.sh'
  workflow_dispatch:

jobs:
  Wazuh-agent-rpm-package-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TYPE: [agent, manager]
        ARCHITECTURE : [x86_64, i386]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        uses: dorny/paths-filter@v2
          id: changes
          with:
            filters: |
              rpm_images:
                - 'rpms/CentOS/**'
                - 'rpms/build.sh'

      - name: Set tag and container name
        run: |
          if [ "${{ steps.changes.outputs.src }}" == "true" ]; then echo "TAG=${{ github.head_ref }}" >> $GITHUB_ENV; else echo "TAG=$(cat $GITHUB_WORKSPACE/VERSION)" >> $GITHUB_ENV ; fi
          if [ "${{ matrix.ARCHITECTURE }}" == "x86_64" ]; then echo "CONTAINER_NAME=rpm_builder_x86" >> $GITHUB_ENV ; else echo "CONTAINER_NAME=rpm_builder_${{ matrix.ARCHITECTURE }}" >> $GITHUB_ENV ; fi

      - name: Download docker image for package building
        if: ${{ ( matrix.ARCHITECTURE == 'x86_64') || ( matrix.ARCHITECTURE == 'i386' ) }}
        run:
          bash $GITHUB_WORKSPACE/.github/actions/common-tools/pull_image_from_ghcr.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor}} $CONTAINER_NAME ${{ matrix.image.DOCKERFILE_PATH }} $TAG

      - name: Build the ${{ matrix.ARCHITECTURE }} rpm Wazuh ${{ matrix.TYPE }} package
        if: ${{ ( matrix.ARCHITECTURE == 'x86_64') || ( matrix.ARCHITECTURE == 'i386' ) }}
        working-directory: ./rpms
        run: |
          bash generate_rpm_package.sh -b master -t ${{ matrix.TYPE }} -a ${{ matrix.ARCHITECTURE }} --dev
          echo "PACKAGE_NAME=$(ls ./output | grep .rpm | head -n 1)" >> $GITHUB_ENV