name: Build Wazuh Packages - DEB - amd64 and i386
on:
  pull_request:
    paths:
      - 'debs/SPECS/*'
      - 'debs/generate_debian_package.sh'
  workflow_dispatch:
  workflow_call:

jobs:
  Wazuh-agent-deb-package-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TYPE: [agent, manager]
        ARCHITECTURE : [amd64, i386]
        exclude:
          - TYPE: manager
            ARCHITECTURE: i386
      fail-fast: false
      continue-on-error: true

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            deb_images:
              - 'debs/Debian/**'
              - 'debs/build.sh'
            deb_packages:
              - 'debs/SPECS/**'
              - 'debs/generate_debian_package.sh'

      - name: Set tag and container name
        run: |
          if [ "${{ steps.changes.outputs.deb_images }}" == "true" ]; then echo "TAG=${{ github.head_ref }}" >> $GITHUB_ENV; else echo "TAG=$(sed 's/\([0-9]*\.[0-9]*\)\.[0-9]*/\1/' $GITHUB_WORKSPACE/VERSION)" >> $GITHUB_ENV ; fi
          echo "CONTAINER_NAME=deb_builder_${{ matrix.ARCHITECTURE }}" >> $GITHUB_ENV

      - name: Download docker image for package building
        run: |
          bash $GITHUB_WORKSPACE/.github/actions/common-tools/pull_image_from_ghcr.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor}} $CONTAINER_NAME ${{ env.TAG }}

      - name: Build the ${{ matrix.ARCHITECTURE }} deb Wazuh ${{ matrix.TYPE }} package
        working-directory: ./debs
        run: |
          REVISION="${{ github.head_ref }}"
          bash generate_debian_package.sh -b master -t ${{ matrix.TYPE }} -a ${{ matrix.ARCHITECTURE }} --dev -j 2 --dont-build-docker --tag ${{ env.TAG }} -r $REVISION
          echo "PACKAGE_NAME=$(ls ./output | grep .deb | head -n 1)" >> $GITHUB_ENV

      - name: Upload Wazuh ${{ matrix.TYPE }} ${{ matrix.ARCHITECTURE }} package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{github.workspace}}/debs/output/${{ env.PACKAGE_NAME }}
          if-no-files-found: error

  Test-install-packages-deb:
    needs: Wazuh-agent-deb-package-builds
    uses: ./.github/workflows/test-install-and-enable-deb.yml
    secrets: inherit