name: Shellcheck code analysis
on: [pull_request]

jobs:
  Shellcheck-for-libraries:
    name: Shellcheck / runner 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ls
        run: |
          ls -la
          ls -la unattended_installer
      - name: Shellcheck
        uses: './.github/actions/shellcheck/'
        with: 
          reporter: github-pr-review
          path: "unattended_installer/test.sh"
          pattern: "*.sh"
          fail_on_error: "false"
          
 
