name: Test install and enable Wazuh agent and manager - RPM
on:
  pull_request:
    paths:
      - 'rpms/SPECS/*'
      - 'rpms/generate_rpm_package.sh'
      - 'rpms/build.sh'
  workflow_dispatch:

jobs:
  Cancel-previous-runs:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action
        with:
          workflow_id: ${{ github.run_id }}

  Test-install-and-enable-rpm-systems:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - imagename: almalinux
            version: 9
            type: agent
          - imagename: oraclelinux
            version: 9
            type: agent
          - imagename: rockylinux
            version: 9
            type: agent
          - imagename: centos
            version: 7
            type: agent
          - imagename: centos
            version: 7
            type: manager
          - imagename: centos
            version: 8
            type: agent
          - imagename: centos
            version: 8
            type: manager
          - imagename: redhat/ubi8
            version: latest
            type: agent
          - imagename: redhat/ubi8
            version: latest
            type: manager
          - imagename: redhat/ubi9
            version: latest
            type: agent
          - imagename: redhat/ubi9
            version: latest
            type: manager
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Setup directories and variables
        run: |
          mkdir $GITHUB_WORKSPACE/packages
          echo 'PACKAGE_NAME=wazuh-${{ matrix.type }}-4.4.0-1.x86_64.rpm' >> $GITHUB_ENV

      - name: Download the Wazuh ${{ matrix.type }} package for ${{ matrix.imagename }}:${{ matrix.version }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create-rpm-packages.yml
          workflow_conclusion: success
          name: $PACKAGE_NAME


      - name: Download the Wazuh ${{ matrix.type }} package for ${{ matrix.imagename }}:${{ matrix.version }}
        working-directory: ./rpms
        run: |
          #curl -o $PACKAGE_NAME https://packages-dev.wazuh.com/pre-release/yum/$PACKAGE_NAME
          mv $PACKAGE_NAME $GITHUB_WORKSPACE/packages

      - name: Launch docker
        run: sudo docker run -v $GITHUB_WORKSPACE/.github/actions/test-install-enable/:/tests -v $GITHUB_WORKSPACE/packages/:/packages ${{ matrix.imagename }}:${{ matrix.version }} bash /tests/install_and_enable.sh $PACKAGE_NAME ${{ matrix.type }}