name: Test
on:
  pull_request:
    paths:
      - 'rpms/CentOS/**'
      - 'rpms/build.sh'
  push:
    branches:
      - master
      - 4.5
      - 4.4
    paths:
      - 'rpms/CentOS/*'
      - 'rpms/build.sh'
  workflow_dispatch:

jobs:
  Build-packages-rpm:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build-rpm-packages.yml
    secrets: inherit