name: Test install and enable Wazuh agent and manager - DEB
on:
  pull_request:
    paths:
      - 'debs/SPECS/*'
      - 'debs/generate_debian_package.sh'
  workflow_dispatch:
  workflow_call:

jobs:

  Wait-for-package-building:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - name: Wait for the package to be built
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Wazuh-agent-deb-package-build
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          interval: 60
          timeoutSeconds: 3600

  Test-install-and-enable-deb-systems:
    needs: Wait-for-package-building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro_name: ['ubuntu:xenial', 'ubuntu:bionic', 'ubuntu:focal', 'ubuntu:jammy', 'debian:stretch', 'debian:buster', 'debian:bullseye']
        type: [agent, manager]
        arch: [amd64, i386]
        exclude:
          - type: manager
            arch: i386
          - distro_name: 'ubuntu:jammy'
            arch: i386
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Setup directories and variables
        run: |
          VERSION=$(cat $GITHUB_WORKSPACE/VERSION)
          REVISION=$( echo ${{ github.head_ref }})
          echo "PACKAGE_NAME=wazuh-${{ matrix.type }}_${VERSION}-${REVISION}_${{ matrix.arch }}.deb" >> $GITHUB_ENV

      - name: Download the Wazuh ${{ matrix.type }} package for ${{ matrix.system.NAME }}
        id: download-artifact
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-deb-packages.yml
          workflow_conclusion: in_progress
          name: ${{env.PACKAGE_NAME}}
          if_no_artifact_found: fail

      - name: Move the Wazuh ${{ matrix.type }} package for ${{ matrix.distro_name }} to the packages directory
        run: |
          mkdir $GITHUB_WORKSPACE/packages
          mv ${{env.PACKAGE_NAME}} $GITHUB_WORKSPACE/packages

      - name: Launch docker
        run: sudo docker run -v $GITHUB_WORKSPACE/.github/actions/test-install-enable/:/tests -v $GITHUB_WORKSPACE/packages/:/packages ${{ matrix.arch }}/${{ matrix.distro_name }} bash /tests/install_and_enable.sh $PACKAGE_NAME ${{ matrix.type }}