name: Test install and enable Wazuh agent and manager - DEB
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Test-install-and-enable-deb-systems:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro_name: ['ubuntu:xenial', 'ubuntu:bionic', 'ubuntu:focal', 'ubuntu:jammy', 'debian:stretch', 'debian:buster', 'debian:bullseye']
        type: [agent, manager]
        arch: [amd64, i386]
        exclude:
          - type: manager
            arch: i386
          - distro_name: 'ubuntu:jammy'
            arch: i386
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Setup directories and variables
        run: |
          VERSION=$(cat $GITHUB_WORKSPACE/VERSION)
          REVISION=${{ github.head_ref }}
          echo "PACKAGE_NAME=wazuh-${{ matrix.type }}_$VERSION-$REVISION_${{ matrix.arch }}.deb" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - uses: Wandalen/wretry.action@master
        name: Download the Wazuh ${{ matrix.type }} package for ${{ matrix.distro_name }}
        with:
          action: dawidd6/action-download-artifact@v2
          with: |
            workflow: build-deb-packages.yml
            workflow_conclusion: in_progress
            name: ${{env.PACKAGE_NAME}}
            if_no_artifact_found: fail
          attempt_limit: 3
          attempt_delay: 2000

      - name: Move the Wazuh ${{ matrix.type }} package for ${{ matrix.distro_name }} to the packages directory
        run: |
          mkdir $GITHUB_WORKSPACE/packages
          mv ${{env.PACKAGE_NAME}} $GITHUB_WORKSPACE/packages

      - name: Launch docker
        run: sudo docker run -v $GITHUB_WORKSPACE/.github/actions/test-install-enable/:/tests -v $GITHUB_WORKSPACE/packages/:/packages ${{ matrix.arch }}/${{ matrix.distro_name }} bash /tests/install_and_enable.sh $PACKAGE_NAME ${{ matrix.type }}