name: Test install and enable Wazuh agent and manager - RPM
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Test-install-and-enable-rpm-systems:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [
        {NAME: 'oraclelinux:9', ARCH: "x86_64"},
        {NAME: 'almalinux:9', ARCH: "x86_64"},
        {NAME: 'rockylinux:9', ARCH: "x86_64"},
        {NAME: 'centos:7', ARCH: "x86_64"},
        {NAME: 'centos:8', ARCH: "x86_64"},
        {NAME: 'i386/centos:7', ARCH: "i386"},
        {NAME: 'redhat/ubi8:latest', ARCH: "x86_64"},
        {NAME: 'redhat/ubi9:latest', ARCH: "x86_64"},
        {NAME: 'amazonlinux:2', ARCH: "x86_64"}]
        type: [agent, manager]
        exclude:
          - system: {ARCH: "i386"}
            type: manager
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Setup directories and variables
        run: |
          VERSION=$(cat $GITHUB_WORKSPACE/VERSION)
          REVISION=$( echo ${{ github.head_ref }} | sed 's/-/./g' )
          echo "PACKAGE_NAME=wazuh-${{ matrix.type }}-$VERSION-$REVISION.${{matrix.system.ARCH}}.rpm" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Download the Wazuh ${{ matrix.type }} package for ${{ matrix.system.NAME }}
        id: download_package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-rpm-packages.yml
          workflow_conclusion: in_progress
          name: ${{env.PACKAGE_NAME}}
          if_no_artifact_found: fail

      - name: Try again to download execution timetable from the last workflow if failed
        if: ${{ always() && steps.download_package.outcome == 'failure' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-rpm-packages.yml
          workflow_conclusion: in_progress
          name: ${{env.PACKAGE_NAME}}
          if_no_artifact_found: fail

      - name: Move the Wazuh ${{ matrix.type }} package for ${{ matrix.system.NAME }} to the packages directory
        run: |
          mkdir $GITHUB_WORKSPACE/packages
          mv ${{env.PACKAGE_NAME}} $GITHUB_WORKSPACE/packages

      - name: Launch docker
        run: sudo docker run -v $GITHUB_WORKSPACE/.github/actions/test-install-enable/:/tests -v $GITHUB_WORKSPACE/packages/:/packages ${{ matrix.system.NAME }} bash /tests/install_and_enable.sh $PACKAGE_NAME ${{ matrix.type }}