name: Test install and enable Wazuh agent and manager - RPM
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Cancel-previous-runs:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action
        with:
          workflow_id: ${{ github.run_id }}

  Test-install-and-enable-rpm-systems:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [{DISTRO: "oraclelinux", VERSION: 9}, {DISTRO: "almalinux", VERSION: 9}, {DISTRO: "rockylinux", VERSION: 9}, {DISTRO: "centos", VERSION: 7, 8}, {DISTRO: "redhat/ubi8", VERSION: latest}, {DISTRO: "redhat/ubi9", VERSION: latest"}]
        type: [agent, manager]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Setup directories and variables
        run: |
          echo 'VERSION=$GITHUB_WORKSPACE/VERSION' >> $GITHUB_ENV
          echo 'PACKAGE_NAME=wazuh-${{ matrix.type }}-${{ env.VERSION }}-test.x86_64.rpm' >> $GITHUB_ENV

      - name: Download the Wazuh ${{ matrix.type }} package for ${{ matrix.system.DISTRO }}:${{ matrix.system.VERSION }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-rpm-packages.yml
          workflow_conclusion: success
          name: $PACKAGE_NAME


      - name: Move the Wazuh ${{ matrix.type }} package for ${{ matrix.system.DISTRO }}:${{ matrix.system.VERSION }} to the packages directory
        working-directory: ./rpms
        run: |
          mkdir $GITHUB_WORKSPACE/packages
          mv $PACKAGE_NAME $GITHUB_WORKSPACE/packages

      - name: Launch docker
        run: sudo docker run -v $GITHUB_WORKSPACE/.github/actions/test-install-enable/:/tests -v $GITHUB_WORKSPACE/packages/:/packages ${{ matrix.system.DISTRO }}:${{ matrix.system.VERSION }} bash /tests/install_and_enable.sh $PACKAGE_NAME ${{ matrix.type }}