name: Test install and enable Wazuh agent and manager - RPM
on:
  pull_request:
    paths:
      - 'rpms/SPECS/*'
      - 'rpms/generate_rpm_package.sh'
  workflow_dispatch:
  workflow_call:

jobs:
  Test-install-and-enable-rpm-systems:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [{DISTRO: "oraclelinux", VERSION: 9}, {DISTRO: "almalinux", VERSION: 9}, {DISTRO: "rockylinux", VERSION: 9}, {DISTRO: "centos", VERSION: 7, 8}, {DISTRO: "redhat/ubi8", VERSION: latest}, {DISTRO: "redhat/ubi9", VERSION: latest"}]
        type: [agent, manager]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Setup directories and variables
        run: |
          VERSION=$(cat $GITHUB_WORKSPACE/VERSION)
          echo "PACKAGE_NAME=wazuh-${{ matrix.type }}-$VERSION-test.x86_64.rpm" >> $GITHUB_ENV

      - name: Download the Wazuh ${{ matrix.type }} package for ${{ matrix.system.DISTRO }}:${{ matrix.system.VERSION }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-rpm-packages.yml
          workflow_conclusion: success
          name: ${{env.PACKAGE_NAME}}
          if_no_artifact_found: fail


      - name: Move the Wazuh ${{ matrix.type }} package for ${{ matrix.system.DISTRO }}:${{ matrix.system.VERSION }} to the packages directory
        working-directory: ./rpms
        run: |
          mkdir $GITHUB_WORKSPACE/packages
          mv ./${{env.PACKAGE_NAME}} $GITHUB_WORKSPACE/packages

      - name: Launch docker
        run: sudo docker run -v $GITHUB_WORKSPACE/.github/actions/test-install-enable/:/tests -v $GITHUB_WORKSPACE/packages/:/packages ${{ matrix.system.DISTRO }}:${{ matrix.system.VERSION }} bash /tests/install_and_enable.sh $PACKAGE_NAME ${{ matrix.type }}