name: Upload package creation Docker images - DEB - amd64 and i386
on:
  pull_request:
    paths:
      - 'debs/Debian/**'
      - 'debs/build.sh'
  push:
    branches:
      - master
      - 4.4
    paths:
      - 'debs/Debian/*'
      - 'debs/build.sh'
  workflow_dispatch:

jobs:
  Upload-deb-package-building-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ {CONTAINER_NAME: deb_builder_amd64, DOCKERFILE_PATH: debs/Debian/amd64}, {CONTAINER_NAME: deb_builder_i386, DOCKERFILE_PATH: debs/Debian/i386}]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Copy build.sh to Dockerfile path
        run:
          cp $GITHUB_WORKSPACE/debs/build.sh $GITHUB_WORKSPACE/${{ matrix.image.DOCKERFILE_PATH }}

      - name: Set tag as version
        run: 
          if [ "${{ github.event_name }}" == "pull_request" ]; then echo "TAG=${{ github.head_ref }}" >> $GITHUB_ENV; else echo "TAG=$(sed 's/\([0-9]*\.[0-9]*\)\.[0-9]*/\1/' $GITHUB_WORKSPACE/VERSION)" >> $GITHUB_ENV; fi

      - name: Build and push image ${{ matrix.image.CONTAINER_NAME }} with tag ${{ env.TAG }} to Github Container Registry
        run:
          bash $GITHUB_WORKSPACE/.github/actions/ghcr-pull-and-push/build_and_push_image_to_ghcr.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor}} ${{matrix.image.CONTAINER_NAME}} ${{ matrix.image.DOCKERFILE_PATH }} ${{ env.TAG }}

  Build-packages-rpm:
    needs: Upload-deb-package-building-images
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build-deb-packages.yml
    secrets: inherit