name: Upload package creation Docker images
on:
  pull_request:
    paths:
      - 'rpms/CentOS/*'
  workflow_dispatch:

jobs:
  Upload RPM x86_64 image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ {CONTAINER_NAME: rpm_builder_x86, DOCKERFILE_PATH: $GITHUB_WORKSPACE/rpms/CentOS/6/x86_64}, {CONTAINER_NAME: rpm_builder_i386, DOCKERFILE_PATH: $GITHUB_WORKSPACE/rpms/CentOS/6/i386}, {CONTAINER_NAME: rpm_builder_aarch64, DOCKERFILE_PATH: $GITHUB_WORKSPACE/rpms/CentOS/7/aarch64}, {CONTAINER_NAME: rpm_builder_ppc64le, DOCKERFILE_PATH: $GITHUB_WORKSPACE/rpms/CentOS/7/ppc64le}, {CONTAINER_NAME: rpm_builder_armv7, DOCKERFILE_PATH: $GITHUB_WORKSPACE/rpms/CentOS/7/armv7hl} ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

  # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.src == 'true'
        name: Build and push image ${{ image.CONTAINER_NAME }} to GIthub Container Registry
        uses: pmorelli92/github-container-registry-build-push@2.0.0
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: ${{ image.CONTAINER_NAME }}
          docker-image-tag: latest
          dockerfile-path: ${{ image.DOCKERFILE_PATH }}/Dockerfile